### ISSUE TITLE
uvgrtp.pc is being install into system path

### ISSUE THREAD

**Issue by ashley-b** [ultravideo/uvgRTP#101]
uvgrtp.pc is being install to system path regardless of CMAKE_INSTALL_PREFIX

```
cmake --install .  --prefix tmp
CMake Error at cmake_install.cmake:59 (file):
  file cannot create directory: /usr/local/lib/pkgconfig.  Maybe need
  administrative privileges.
```

https://github.com/ultravideo/uvgRTP/blob/dea14a3e98a1d843a6ff499d493f44a19730b743/CMakeLists.txt#L182

Maybe it should be this ?
```
install(FILES ${CMAKE_CURRENT_BINARY_DIR}/uvgrtp.pc DESTINATION lib/pkgconfig)
```

**Comment by fador** [comment]
sorry for the delay, I fixed the path issue 😅
