### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by bcizmeci** [ultravideo/uvgRTP#102]
Hi ultravideo developers,

Do you have any plans to support IPv6 option for the internet layer protocol? 

Best,
Burak

**Comment by jrsnen** [comment]
Hi again,

yes, IPv6 support would be preferred. I actually ran into problems with this last week, so there is a need to support this on our end as well. I haven't gotten around to what this would take yet, since there is much other work around uvgRTP that needs doing.

Also, I got your email, I will respond to it probably at the start of next week.

BR, Joni

**Comment by bcizmeci** [comment]
Hi Joni,

We have implemented this featue and a PR will be made.

Best,
Burak

**Comment by jrsnen** [comment]
@bcizmeci That sounds great! I don't think any of us have had the time to implement this, and I also have need for this feature down the line.

BR, Joni

**Comment by devenvexe** [comment]
@bcizmeci is your PR available?

**Comment by bcizmeci** [comment]
Unfortunately, it is not ready. One of my students created it but it needs some more work to be a proper PR.

**Comment by jrsnen** [comment]
Hi @bcizmeci 

Do you have any time estimate on when the PR would be ready? I've been making uvgRTP ready for 2.1.0 release and IPv6 support would be very nice feature for this release.

BR, Joni

**Comment by bcizmeci** [comment]
Hi @jrsnen Joni,

I didn't have time on it but one of my colleagues is going to start working on it again in November. If you want to have a look, I can put it on a branch. 

BR,
Burak

**Comment by jrsnen** [comment]
@bcizmeci thanks for the info.

Thanks for the info! I'm not in a terrible hurry. We'll release 2.1.0 without IPv6 support, and then IPv6 support can be released in 2.2.0 or later.

BR, Joni

**Comment by jrsnen** [comment]
@devenvexe @bcizmeci Good news. We have implemented IPv6 support, and it will be part of uvgRTP soon with the next release.

**Comment by tampsa** [comment]
Implemented by release 2.3.0
