### ISSUE TITLE
Pull_frame() not working

### ISSUE THREAD

**Issue by wowaser** [ultravideo/uvgRTP#103]
Hello,

I have pulled the most recent updates (The ones starting from 2cb5928), and now none of my code seems to work. The problem is with the pull_frame, as it always returns nothing. None of the examples seem to work as well. 

This very basic example does not produce any output for me: 
```
#include <uvgrtp/lib.hh>

int main(void)
{
    uvgrtp::context ctx;
    uvgrtp::session *sess = ctx.create_session("127.0.0.1");

    uvgrtp::media_stream *strm = sess->create_stream(8888, 8888, RTP_FORMAT_GENERIC, RTP_NO_FLAGS);

    char *message  = (char *)"Hello, world!";
    size_t msg_len = strlen(message) + 1;

    for (;;) {
        strm->push_frame((uint8_t *)message, msg_len, RTP_NO_FLAGS);
        auto frame = strm->pull_frame();
        fprintf(stderr, "Message: '%s'\n", frame->payload);
        uvgrtp::frame::dealloc_frame(frame);
    }
}
```
Output (or lack there of):
![image](https://user-images.githubusercontent.com/70014877/154804955-e2ea7dac-29a3-487c-b06e-95987c49eb0d.png)

I build my uvgrtp _with_ crypto, if that makes any difference. Release does not work either

Thanks

**Comment by jrsnen** [comment]
Fixed by f483cbaa81a6fa443e4cd0ff0bee84502beb11be, sorry about that. Added automated test to make sure poll always returns something to avoid breaking pull_frame in the future.
