### ISSUE TITLE
RFC 3550 RTCP: The stopping and exiting

### ISSUE THREAD

**Issue by jrsnen** [ultravideo/uvgRTP#111]
Currently, I don't think the BYE packet is ever sent. The code still needs improvements on how to handle multithreading.

https://github.com/ultravideo/uvgRTP/blob/cce653b9b7fb26e52d7edd436a5ab9eeae328d30/src/rtcp.cc#L97

**Comment by jrsnen** [comment]
BYE is now sent, but there is no socket management, so the exiting is not handled well.

**Comment by tampsa** [comment]
Fixed by 8b3701b814628b8349378a5df06baf9c1f78682c and 767c504d9b80917fa8be0509650b3d0c38c82dfd
