### ISSUE TITLE
Is TTL supported ?

### ISSUE THREAD

**Issue by lafoletc** [ultravideo/uvgRTP#116]
how can I configure TTL value ?

**Comment by jrsnen** [comment]
Hi.

Unfortunately, it doesn't seem to possible at the moment. Adding a flag [here](https://github.com/ultravideo/uvgRTP/blob/33f6260478d0a360c7d59f06c01b623d840a0fcc/include/uvgrtp/util.hh#L239) and implementing it [here](https://github.com/ultravideo/uvgRTP/blob/33f6260478d0a360c7d59f06c01b623d840a0fcc/src/media_stream.cc#L499) by calling setsocketopt with correct parameters would solve this issue. You are welcome to make a PR if you want to help the community.

BR, Joni

**Comment by jrsnen** [comment]
The concept of TTL does not make sense in UDP and RTP is entirely UDP based protocol. Closing...
