### ISSUE TITLE
Start code lookup (SCL) is not performed for small Intra frames?

### ISSUE THREAD

**Issue by jrsnen** [ultravideo/uvgRTP#117]
I was testing low bit rate videos and came across an issue where the NAL units of an Intra frame were transmitted and given to the user as one chunk instead of separate NAL units. This issue seems  to appear when the Intra frame size is less than allowed packet size.

The fix would be to make sure that Start Code Lookup is also performed when the Intra frame is below the packet size limit. ([here](https://github.com/ultravideo/uvgRTP/blob/66feedf532eb63469f6be872be8c07db6189fd13/src/formats/h26x.cc#L285)).

Related: #119

**Comment by altonen** [comment]
Can't comment on the exact issue here but one very annoying and semi-obscure bug I fixed long time ago had to do with this line:
https://github.com/ultravideo/uvgRTP/blob/984647cad6176ca24a12e5b8b8c8e370a153c225/src/formats/h265.cc#L90

The check `data_len - 3 <= payload_size` has now been replaced with `data_len <= payload_size`. Honestly, I don't even remember what that check fixed but without with out random frames started dropping and it also seems to relate to single NAL units. I don't know why the condition has been changed and whether the bug (whatever it was) was fixed elsewhere but that was one really annoying and time-consuming bug to fix. But like I said, not sure if it has anything to do with this bug.

**Comment by jrsnen** [comment]
@altonen thanks for the tip, I'll keep that in mind when I investigate this further.

Here is what I've gathered so far: The tests fail in an amazing coincidence due to the test data being "aaaaaaa" which translates to 97, which bit shifted happens to be 48 which is the payload type for aggregate packet resulting in a crash before the safety check I added yesterday. The best fix for this would probably be not to send data that does not have a NAL header, since the single NAL unit's packet payload is supposed to start with a copy of the NAL header.

This explains the test failure, but I haven't yet figured out the final reason why the single NAL units work poorly when the NAL start code is present or how to fix this issue.

**Comment by jrsnen** [comment]
Ok, I think I finally figured out what the problems were exactly:

1) uvgRTP accepts packets without start code, which can lead to issues in receiving end and cannot be correct when looking at the RFC because the start code is needed by RFC for single NAL unit packages. These should be rejected instead.

2) If the packet size is less than allowed payload size, no start code lookup seems to be performed and the packet is just transmitted as is (Intra + VPS + SPS + PPS). I'm not sure if this is incorrect, but it was causing issues, since I'm verifying that all necessary packets have arrived before showing the stream based on the start codes. No data seems to be lost, though, which is good.

Neither of these issues is important enough for me to spend time on them, but I will make a new issue for 1) and modify this to reflect 2).

**Comment by jrsnen** [comment]
SCL for small frames was included in 84e65f58eb80b59cd77d8f79354173e6393f01a4
