### ISSUE TITLE
Rtcp sender reports do not contain any blocks

### ISSUE THREAD

**Issue by wowaser** [ultravideo/uvgRTP#125]
Hello

To reproduce the error you can run the example code from here: https://github.com/ultravideo/uvgRTP/blob/master/examples/rtcp_hook.cc

```cpp
void sender_hook(uvgrtp::frame::rtcp_sender_report *frame)
{
    std::cout << "RTCP sender report! ----------"       << std::endl;
    std::cout << "NTP msw: "        << frame->sender_info.ntp_msw   << std::endl;
    std::cout << "NTP lsw: "        << frame->sender_info.ntp_lsw   << std::endl;
    std::cout << "RTP timestamp: "  << frame->sender_info.rtp_ts    << std::endl;
    std::cout << "packet count: "   << frame->sender_info.pkt_cnt   << std::endl;
    std::cout << "byte count: "     << frame->sender_info.byte_cnt  << std::endl;

    for (auto& block : frame->report_blocks)
    {
        std::cout << "ssrc: "       << block.ssrc     << std::endl;
        std::cout << "fraction: "   << block.fraction << std::endl;
        std::cout << "lost: "       << block.lost     << std::endl;
        std::cout << "last_seq: "   << block.last_seq << std::endl;
        std::cout << "jitter: "     << block.jitter   << std::endl;
        std::cout << "lsr: "        << block.lsr      << std::endl;
        std::cout << "dlsr (ms): "  << uvgrtp::clock::jiffies_to_ms(block.dlsr)
                  << std::endl << std::endl;
    }

    /* RTCP frames can be deallocated using delete */
    delete frame;
}

```
In the above function, only the data from frame->sender_info gets printed out, and the report_blocks are empty.

**Comment by jrsnen** [comment]
Hello!

Is this instance receiving? I'm not an expert on RTCP, but my understanding is that report blocks can be empty if the instance that sends the report has not received anything.

I'm starting to use RTCP myself, and I will try to upload all fixes I make to this repo at some point.

**Comment by wowaser** [comment]
If you mean if it's receiving RTP then no. This is just the rtcp hook from the uvgRTP example I linked earlier. But why is there a separate sender report handling at all, if it only activates when it becomes a receiver?

**Comment by jrsnen** [comment]
Sender reports (SR) are sent from instances that are sending (and possibly receiving). Receiver reports are sent from instances that are only receiving, but not sending. 

If you have a sender that is not receiving, then that sender sends SRs without report blocks (that are about receiving RTP). This is at least my understanding of RFC 3550.

**Comment by wowaser** [comment]
Okay, thank you for the clarification.
