### ISSUE TITLE
RCE_NO_H26X_SCL used in push_frame?

### ISSUE THREAD

**Issue by wowaser** [ultravideo/uvgRTP#131]
Hello, 

As far as I understand, _push_frame_ function takes RTP_FLAGS as a parameter. And RTP_CTX_ENABLE_FLAGS are passed to _create_stream_ function. 

However, the only way for the RCE_NO_H26X_SCL flag to take effect, is to pass it to the _push_frame_ function. Passing it when creating the stream does nothing. This is because it is evaluated from the _flags_ variable of the _push_frame_ function: 
![image](https://user-images.githubusercontent.com/70014877/175315944-68c07efc-db25-4d40-970e-24da49871684.png)

Is this the intended use? And if so, can I use other RTP_CTX_ENABLE_FLAGS on a per-frame basis? 

I was struggling for some time trying to get the RCE_NO_H26X_SCL flag to work.

**Comment by jrsnen** [comment]
@wowaser This is probably a bug. I must have gotten confused with all the different flags as they are all just named flags. It should use the enable flags, not the frame flags.
