### ISSUE TITLE
Incorrect lsr calculation

### ISSUE THREAD

**Issue by LeeTaekLim** [ultravideo/uvgRTP#132]
Hi, I think I found an error while trying to measure network delay from rtcp. Calculating lsr in `handle_sender_report_packet()` which is included in `rtcp.cc` seems to be wrong.
According to `rtcp.cc`,
`participants_[frame->ssrc]->stats.lsr = ((frame->sender_info.ntp_msw >> 16) & 0xffff) |
  ((frame->sender_info.ntp_lsw & 0xffff0000) >> 16);`
but I think the following code is correct because lsr is middle 32 bits of the 64-bit NTP timestamp of previous SR.
`participants_[frame->ssrc]->stats.lsr =
        ((frame->sender_info.ntp_msw & 0xffff) << 16) |
        (frame->sender_info.ntp_lsw >> 16);`

Could you tell me which one is right? 
Also is there any way to measure network delay or latency from rtcp? I'm not professional so I have had hard time implementing that feature. I tried to write code based on "Figure 2: Example for round-trip time computation" in RFC 3550 but it would be very happy for me to find any other way.

**Comment by jrsnen** [comment]
Hello and thank you for creating this issue. I haven't yet gotten around to using/testing this particular feature of RTCP, so I would assume you are correct if you think there is an error. Unfortunately, I don't have the time to dive deep into this issue at the moment.

As for the network delay, the challenge comes from the accuracy of the NTP synchronization of clocks on two different machines. If they are sufficiently synchronized, calculating the latency should be easy. Also, some round-trip method vial RTCP could be possible, but I have not yet attempted to solve this problem, so I'm afraid I cannot help much with this. 

In our paper, we calculated the round-trip latency by sending RTP packets back immediately.

**Comment by jrsnen** [comment]
@LeeTaekLim can this be closed or do you have more questions?

- Joni

**Comment by jrsnen** [comment]
Actually, it's probably better if you open a new issue for new questions. Fixed by 4db794c51d216e2ae4efe01a4afe341a3838e150
