### ISSUE TITLE
RFC 6189: ZRTP timing

### ISSUE THREAD

**Issue by jrsnen** [ultravideo/uvgRTP#147]
The timing of ZRTP messages is not as exact as it should be. This does not actually interfere with ZRTP operations, but should be fixed at some point so that it follows the RFC. 

As an example, this kind of timing is implemented in [RTCP](https://github.com/ultravideo/uvgRTP/blob/1b53b6f443105cacfec7fb60a9b729520ffec40e/src/rtcp.cc#L200).

The issue is found [here](https://github.com/ultravideo/uvgRTP/blob/1b53b6f443105cacfec7fb60a9b729520ffec40e/src/zrtp.cc#L347), [here](https://github.com/ultravideo/uvgRTP/blob/1b53b6f443105cacfec7fb60a9b729520ffec40e/src/zrtp.cc#L440), [here](https://github.com/ultravideo/uvgRTP/blob/1b53b6f443105cacfec7fb60a9b729520ffec40e/src/zrtp.cc#L480), [here](https://github.com/ultravideo/uvgRTP/blob/1b53b6f443105cacfec7fb60a9b729520ffec40e/src/zrtp.cc#L514), [here](https://github.com/ultravideo/uvgRTP/blob/1b53b6f443105cacfec7fb60a9b729520ffec40e/src/zrtp.cc#L551) and [here](https://github.com/ultravideo/uvgRTP/blob/1b53b6f443105cacfec7fb60a9b729520ffec40e/src/zrtp.cc#L588).

**Comment by tampsa** [comment]
Fixed by 0d87863
