### ISSUE TITLE
RFC 3550 RTCP: API for sending APP packets

### ISSUE THREAD

**Issue by wowaser** [ultravideo/uvgRTP#155]
> Some sort of hook based API would probably be better for APP sending than the current one.

_Originally posted by @jrsnen in https://github.com/ultravideo/uvgRTP/issues/144#issuecomment-1188862016_

I am very interested in this functionality. Not sure about the hook part, but at least I would like to see the following features exposed to the user:

- Getting the size of deque of a certain APP packet type
- Being able to clear that deque OR
- Having some sort of **latest_only** flag that will prevent packets from accumulating
- (Maybe even having full access to the deque?)

I want to implement this, because I assume this is not your top priority right now. Before I start I would like to hear your thoughts on it, @jrsnen

**Comment by jrsnen** [comment]
@wowaser I can see two approaches to APP management. 

1) The hook approach would be that uvgRTP asks user for APP packets when sending the RTCP packet, similarly to how other RTCP packets work. The user would only have to make sure the data is ready when hook is called.

2) As you are suggesting, have user manage the deque in various ways. To me, this seems the more complicated of the two, especially from user's perspective.

I'm not against having one or both in uvgRTP, similarly how for receiving RTP packets, there are two options. Out of these, the flag makes the most sense to me. Others I can also see as an option, but also add complexity to uvgRTP API, which is undesirable.

**Comment by tampsa** [comment]
Fixed by 02f660a56182db6d2ef0b4f68c4fdb7f875a4791
