### ISSUE TITLE
RFC 5761: Multiplexing RTP Data and Control Packets on a Single Port

### ISSUE THREAD

**Issue by kar8uncle** [ultravideo/uvgRTP#160]
This is regarding RTCP receiver report (pt=73 or 201) I am receiving but I believe it applies to other RTCP packets as well.

In my setup, both RTP and RTCP packets are received at the same port. In `uvgrtp::rtcp::recv_packet_handler`, it seems to be collecting statistics about a remote sending peer. However, in my case, the remote peer is receive-only, and the packets I receive are RTCP receiver reports, but statistics are being collected which is incorrect.

I also don't seem to get any receiver callbacks from the real RTCP object of the stream.

**Comment by jrsnen** [comment]
Hello!

Unfortenately, receiving RTP and RTCP in the same port has not been implemented. We warmly welcome PR's for this feature, but it is unlikely that anyone from our group will implement this.

Best Regards, 
Joni Räsänen

**Comment by jrsnen** [comment]
There is an RFC for this feature: https://datatracker.ietf.org/doc/html/rfc5761

**Comment by tampsa** [comment]
Implemented by efe7d98
