### ISSUE TITLE
Linux debug/release logs and optimization

### ISSUE THREAD

**Issue by wowaser** [ultravideo/uvgRTP#161]
Hello,

I am running uvgrtp on Linux and it prints out all the [uvgRTP][DEBUG] logs. I assume that optimization flags are also not set. I can't seem to find the file where I could set those flags and make uvgRTP silent. I looked through the CMake files and found nothing

I built the same way as always (as described in BUILDING.md), but before the logs were not present.

**Comment by jrsnen** [comment]
Hi,

I remember wondering the same few weeks ago and came to the conclusion that the correct build type was used, but it was just the prints that were incorrect, but I may also be mistaken.

There is a build flag for silencing the prints.

I will take a closer look at this issue at some point if no one else has time.

BR, Joni

**Comment by wowaser** [comment]
Where is that build flag found?

**Comment by jrsnen** [comment]
Ok, sorry, there is no build flag yet. I have it in a branch I'm still working on (I will push it hopefully this week). The way to disable prints is to define __RTP_SILENT__ in build environment.

**Comment by jrsnen** [comment]
@wowaser I've now added the option for completely silencing uvgRTP prints. It is called DISABLE_PRINTS. I also found out that no build type was selected by default on Linux with CMake. I set the Debug build type to be the default on Linux, with switching possible using CMAKE_BUILD_TYPE.

You can see [updated build instruction](https://github.com/ultravideo/uvgRTP/blob/master/BUILDING.md) for more details.
