### ISSUE TITLE
PTS & DTS

### ISSUE THREAD

**Issue by SANDRUX** [ultravideo/uvgRTP#162]
does this library support setting up  DTS and PTS for packages? 
I want to stream an encoded packet from FFmpeg, but it seems like I need to do it manually, so I prefer to find a way to handle this in the RTP library.

**Comment by jrsnen** [comment]
Hi.

There is no native support for timestamps unless they are included in a supported RFC. uvgRTP does however support setting the RTP timestamp of a frame in push_frame, but we haven't tested this functionality (currently wondering should it be NTP timestamp or RTP timestamp that is set this way). Using the RTCP, one can get the NTP timestamp corresponding to the RTP timestamp, but there is an issue that this is actually calculated and not sampled from RTP timestamps as it should be (#136).

Another alternative that comes into mind is embedding the timestamp into SEI message, but that is outside the scope of uvgRTP.

**Comment by SANDRUX** [comment]
Thank you so much, I've already figured out how to set timestamps for the RTP stream, and works fine. 
Pretty cool and useful lib though, good work guys ❤️
