### ISSUE TITLE
Best approach to send images?

### ISSUE THREAD

**Issue by esteimle** [ultravideo/uvgRTP#169]
I compiled uvgRTP for Android, and then also on a linux box. I ported the send_generic example into my Android app and was able to use it to send packets to receiving_hook running on my linux machine. Now I want to try to send images, like an MJPEG stream, just one image after another. Should I be feeding the whole image buffer to push_frame or should I be breaking the image up into packet size chunks and feeding them one at a time?

Thanks!

**Comment by esteimle** [comment]
Nevermind I figured it out :)  Just had to set the flags correct between those two demos.

**Comment by bcizmeci** [comment]
@esteimle Although this issue is closed, this is an interesting topic. 
How is it possible to compile uvgRTP on Android?
