### ISSUE TITLE
Dead link for public API documentation

### ISSUE THREAD

**Issue by wowaser** [ultravideo/uvgRTP#17]
In the Documentation file (https://github.com/ultravideo/uvgRTP/blob/master/docs/README.md#public-api) the chapter "Public API" has a broken link to the API documentation. You should replace the .com extension with .io extension.

**Comment by polusto** [comment]
Thanks for noticing. Fixed by e7be4f7d899aa30a479bcc5324a86fc659611373

**Comment by polusto** [comment]
Updated the link to doxygen
