### ISSUE TITLE
RFC 6184 5.7.1: Single-Time Aggregation Packet (STAP)

### ISSUE THREAD

**Issue by jrsnen** [ultravideo/uvgRTP#176]
uvgRTP H264 has no aggregate packets implemented, I feel at least the STAP packet would be beneficial to implement to increase compatibility with other software.

The sending side would need reimplementing add_aggregate_packet()-function and finalize_aggregation_pkt() function in formats/h264.

The receiving side may need reimplementation of handle_aggregation_packet() in formats/h264 if the h26x implementation does not work correctly.

**Comment by tampsa** [comment]
Fixed by 3942f9d
