### ISSUE TITLE
Building in Visual Studio 14 fails

### ISSUE THREAD

**Issue by ingura** [ultravideo/uvgRTP#181]
Hi ,  

I have an issue: Cmake generates the x64 project files without a complaint. When moving to build on VS 14 here is the result: 

```
6>  srtcp.cc
6>  wrapper_c.cc
6>  Generating Code...
8>------ Build started: Project: ALL_BUILD, Configuration: Debug x64 ------
8>  Building Custom Rule D:/workBench/TestsLibs/_Fresh/Streaming/uvgRTP-master/CMakeLists.txt
9>------ Skipped Build: Project: INSTALL, Configuration: Debug x64 ------
9>Project not selected to build for this solution configuration 
10>------ Skipped Build: Project: PACKAGE, Configuration: Debug x64 ------
10>Project not selected to build for this solution configuration 
========== Build: 7 succeeded, 1 failed, 0 up-to-date, 2 skipped ==========
```
Specifically there are 4 error preventing uvgrtp project from building:
![image](https://user-images.githubusercontent.com/103531218/205202511-f5fe8503-7a8b-4aa6-8ec4-b03a58f23868.png)

What could be the issue here?
Thank you

**Comment by ingura** [comment]
Thank you

**Comment by ingura** [comment]
Yes VS 14 needs a little bit of hand holding. For anyone else having the same issue replace:

list   { ssrc_, ourItems_ } with chunk  as follows:

```
uvgrtp::frame::rtcp_sdes_chunk chunk = uvgrtp::frame::rtcp_sdes_chunk();
chunk.ssrc = ssrc_;
chunk.items = ourItems_;
...
!construct_sdes_chunk(frame, write_ptr, chunk)
```

The later 2 issues are const void *  casting issues that get resolved by replacing 

`inet_ntop(AF_INET, &addr.sin_addr, c_string, INET_ADDRSTRLEN)`

with 
```
                const void* voidPinAddr;
		voidPinAddr = &addr.sin_addr;
		PVOID pvoidInAddr = const_cast<PVOID>(voidPinAddr);
		inet_ntop(AF_INET, pvoidInAddr, c_string, INET_ADDRSTRLEN);
```

**Comment by jrsnen** [comment]
Thanks! I also added these fixes to the master. Can you verify that f407cdbe8d08f47df754a2d6f65992ecdc095ffd fixes these issues?

**Comment by ingura** [comment]
Yes, thank you!

**Comment by jrsnen** [comment]
Thanks!
