### ISSUE TITLE
RTCP failure handling

### ISSUE THREAD

**Issue by jrsnen** [ultravideo/uvgRTP#183]
It would be nice if RTCP would monitor if a stream drops and would gracefully remove that participant.

**Comment by wowaser** [comment]
Do you mean a sort of timeout mechanism that will drop the participant after it has been unresponsive N seconds?

**Comment by jrsnen** [comment]
@wowaser something like that. Based on your comment from #180:

> When one side crashes and is restarted, the RTCP goes crazy. Functionally, RTP and RTCP still work, because they are connectionless. This is because when restarted, the stream gets new random SSRC and starts sending RR/SR and other RTCP packets with that SSRC. If the receiver is restarted, the sender side spams this (the "new" incomplete participant does not have a socket allocated): ![image](https://user-images.githubusercontent.com/70014877/205181821-e371f8ce-c05f-4b04-acd5-28902e4050ac.png) If the sender is restarted, the receiver side spams this: ![image](https://user-images.githubusercontent.com/70014877/205181919-4d3fd5fa-86b0-43ca-a9d5-8223eb1f19df.png)
> 
> **In both cases, the RTCP thread on the receiver side never exits, even after destructors are called and everything goes out of scope.**

This situation could most likely be handled better. I have not fully investigated all the issues related to this.

**Comment by wowaser** [comment]
Well, the one with sockets happens because the participant is added not on stream initialization, but as a "dummy" after the RR/SR from it is received. So no sockets have been created for that SSRC and it starts complaining about that

**Comment by tampsa** [comment]
Fixed by 767c504d9b80917fa8be0509650b3d0c38c82dfd
