### ISSUE TITLE
Get configure values

### ISSUE THREAD

**Issue by jrsnen** [ultravideo/uvgRTP#184]
It is possible to configure certain aspects of uvgRTP using the configure_ctx()-function in media_stream, but there is no way to programmatically query these values for the user. A new function should be added for this task. 

The first though for the name is configure_value(), but I'm open to other suggestion. I guess the traditional way to name these are set_conf_value and get_conf_value, which could also be done, just make the current function call one of those and remove it from documentation.

**Comment by tampsa** [comment]
Implemented by 655294e
