### ISSUE TITLE
H265 Failed to flush the message queue

### ISSUE THREAD

**Issue by jrsnen** [ultravideo/uvgRTP#205]
> I would like to jump in to this question because I encountered the same error messages for a specific HEVC configuration (NVENC). I also tried to increase the buffer sizes to 80 MB for RCV & SND 16 MB for RING buffer size but increasing the buffer sizes doesn't help at all.
> 
> The error messages periodically happening when the encoder triggers intra refresh. More specifically, I set intra_refresh_period: 250 intra_refresh_count: 50
> 
> I validated this behaviour with different parameters. When the intra refresh is disabled, the error messages are not printed and there aren't any artifacts in the video.

Commented by @bcizmeci at https://github.com/ultravideo/uvgRTP/issues/201#issuecomment-1679705246

**Comment by bcizmeci** [comment]
Thanks a lot! We are looking forward to integrate the new version and let you know if we encounter any new issues with it.

**Comment by jrsnen** [comment]
Thanks! We think this was fixed by fixing fragmentation of multiple NAL units in the same access units, but let us know if the issues continue.

BR, Joni
