### ISSUE TITLE
Visual Studio Library Linking Documentation

### ISSUE THREAD

**Issue by dagrooms52** [ultravideo/uvgRTP#208]
I just worked through building this project and linking it in Visual Studio, and wanted to share some helpful info that could be added to the Building docs.
After linking the headers and library to my project, I tried to compile the following line of code from the listener hook example:
```cpp    
(void)uvgrtp::frame::dealloc_frame(frame);
```
And got the following linker errors:
```
uvgrtp.lib(socket.obj) : error LNK2001: unresolved external symbol in6addr_any
uvgrtp.lib(hostname.obj) : error LNK2019: unresolved external symbol __imp_GetUserNameA referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl uvgrtp::hostname::get_username(void)" (?get_username@hostname@uvgrtp@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ)
```

I ended up needing to add `ws2_32.lib` and `Advapi32.lib` to the Linker > Input > Additional Dependencies panel. The final working entry in that field is `uvgrtp.lib;ws2_32.lib;Advapi32.lib`

**Comment by jrsnen** [comment]
Hi,

I assume you are not using CMake? I guess we could add a few words about this, but I think CMake should handle this automatically.

BR, Joni

**Comment by jrsnen** [comment]
I added mention of this to BUILDING.md. This will be pushed soon.
