### ISSUE TITLE
Not Receiving RTP Packets from FFmpeg

### ISSUE THREAD

**Issue by dagrooms52** [ultravideo/uvgRTP#209]
I'm running the example code for the polling receiver and attempting to read RTP packets sent from ffmpeg using the following command:
```sh
ffmpeg -re -stream_loop -1 -i .\myvideo.mp4 -an -f rtp rtp://localhost:14588
```
I verified in Wireshark that the RTP packets are being sent to port 14588 as UDP. Wireshark does not recognize them with a "rtp" filter applied, only "udp".

The RTP [polling receiver](https://github.com/ultravideo/uvgRTP/blob/master/examples/receiving_poll.cc) does not see any RTP packets emitted from ffmpeg. I copied the example directly but will paste some code I'm using:
```cpp
constexpr uint16_t LOCAL_PORT_RTP = 14588;
constexpr char LOCAL_ADDRESS[] = "127.0.0.1";
...
uvgrtp::context ctx;
uvgrtp::session* sess = ctx.create_session(LOCAL_ADDRESS);
int flags = RCE_RECEIVE_ONLY;

uvgrtp::media_stream* receiver = sess->create_stream(LOCAL_PORT_RTP, RTP_FORMAT_GENERIC, flags);
while (true) {
    uvgrtp::frame::rtp_frame* frame = receiver->pull_frame(100);
    if (frame) std::cout << "Received frame\n"; 
}
```

I tested with the uvgrtp [example sender](https://github.com/ultravideo/uvgRTP/blob/master/examples/sending.cc) and found that the uvgrtp client recognized the packets immediately. Wireshark also recognizes these with the "udp" filter but not with "rtp".
```cpp
int flags = RCE_SEND_ONLY;
uvgrtp::media_stream* hevc = sess->create_stream(REMOTE_PORT, RTP_FORMAT_H264, flags);
// build fake frame...
// in loop with 1s delay between iterations:
hevc->push_frame(std::move(dummy_frame), PAYLOAD_LEN, RTP_NO_FLAGS);
```

How can I read FFmpeg's flavor of RTP packets, and what's the difference with the ones emitted by the uvgrtp sender?
This is on Windows, so has to do with the underlying winsock usage. I compiled uvgrtp in Visual Studio.

**Comment by dagrooms52** [comment]
It appears that winsock is not even seeing the UDP packet from ffmpeg. In line 451 of `reception_flow.cc` I see that `pfds->revents == 0`, so there is no data to start processing. This is truly strange as I see UDP packets going to the same port when I run ffmpeg and the uvgrtp sender, but in the case of ffmpeg winsock is not getting any packets.

**Comment by dagrooms52** [comment]
I found that WSARecvFrom was failing with code [10040 WSAEMSGSIZE](https://support.microsoft.com/en-us/topic/46b4779c-33dd-09ed-4cde-73e5064e7bd8).
On line 874 of socket.cc I increased the buffer length by 8 and it is now capable of handling ffmpeg's RTP packets. I imagine there's more data coming in than was used to compute `buf_len`, which was causing it to fail. I can continue with my patch but it's probably worth finding out why the buffer is too short.

**Comment by altonen** [comment]
If you try to increase in `RCC_MTU_SIZE, does it work then? IIRC FFmpeg sent a few extra bytes over 1500 which caused issues but I can't find a reference for it now

**Comment by jrsnen** [comment]
Hello,

@dagrooms52 what is the situation with this? I think @altonen meant reducing the MTU size in uvgRTP so that they fit when the MTU size of the network is smaller than the default size in uvgRTP. We are currently working on a paper, but after that we can get more involved in helping with issues.

BR, Joni

**Comment by jrsnen** [comment]
As I am reading the issue, it indeed seems that either decreasing the sending side MTU or increasing the receiving side MTU is the answer. This buf_len value is determined said RCC_MTU_SIZE flag. This can be changed with configure_ctx function in media_stream. I'm closing this issue.

Better default MTU size values can be suggested, but increasing means that it does not pass through all connections. It still might be worth it though if it means we operate better with ffmpeg.

BR, Joni
