### ISSUE TITLE
APP packet handling

### ISSUE THREAD

**Issue by wowaser** [ultravideo/uvgRTP#21]
Hello again,
I am trying to send APP packets for testing purposes. The output is the following: 
![image](https://user-images.githubusercontent.com/70014877/120150472-c4543a00-c1f3-11eb-94d1-39a953681aaa.png)

I dug around and the problem is that you define frame types in the enum like so:
![image](https://user-images.githubusercontent.com/70014877/120150603-ebab0700-c1f3-11eb-8d59-1038ef76b3fd.png)

But the handler in the **rtcp::handle_incoming_packet** sets the max on BYE packet, whereas in reality max is the APP packet.
![image](https://user-images.githubusercontent.com/70014877/120150874-447a9f80-c1f4-11eb-99b9-d280b611c8d5.png)

I don't know if I should create pull requests for such minor fixes, please let me know. 

Thank you

**Comment by fador** [comment]
Hi,

Great to see that someone is finding the problems in the code, since we have not utilized all of the features in our testing =)
Actually it would help if you can submit a pull request!

**Comment by wowaser** [comment]
Hm, it turned out it's not so trivial to fix this. I am unable to submit a pull request rn, sorry.

**Comment by fador** [comment]
No worries, we try to look into this at some point!

**Comment by polusto** [comment]
@wowaser can you describe what issues you ran into? I'm doing a high level refactoring of uvgRTP and perhaps there is something I can do to make the changes easier.

**Comment by wowaser** [comment]
I thought that just changing _pkt_type > uvgrtp::frame::RTCP_FT_BYE_ to _pkt_type > uvgrtp::frame::RTCP_FT_APP_ would solve the issue, but I guess there's something else that needs to be done(like recompiling the lib maybe?).

**Comment by wowaser** [comment]
Yeah, I rebuilt the uvgrtp solution after changing 
pkt_type > uvgrtp::frame::RTCP_FT_BYE 
to 
pkt_type > uvgrtp::frame::RTCP_FT_APP, and now it crashes right away when I try to send an APP packet, because of a memory read access violation in the _rtp_error_t uvgrtp::rtcp::handle_app_packet_

**Comment by polusto** [comment]
Thanks again for the pull request!
