### ISSUE TITLE
rtcp_sender_report::report_blocks is always empty

### ISSUE THREAD

**Issue by wowaser** [ultravideo/uvgRTP#219]
Hello,

As the title says, there is no content to the rtcp_sender_report. This issue can be replicated with **examples/rtcp_hook.cc**.  

A couple more questions: 
What is the intended way of calculating the packetloss? Do the values **rtcp_report_block::fraction** and **rtcp_report_block:lost** convey the same information but fraction is basically total / lost?

**Comment by wowaser** [comment]
Thanks!
Just to clarify, if I have a one-way stream, what does receiver_report report as loss? So, if I am streaming video and I want the receiver to have information about lost video packets, do I need to parse the receiver_report on the sender side and then send it to the receiver (as an APP packet for example)?

**Comment by jrsnen** [comment]
Loss is basically a sequence number that has not arrived. I don't currently remember the details in uvgRTP for this.

Usually it is the sender who is interested in how many of its packets are being lost so it can react. The data does exist inside uvgRTP receiver, but currently there is no way to retrieve it. Using APP packet is probably the easiest way to do this, but it certainly is not the intended way.

**Comment by wowaser** [comment]
Okay, thank you for clarification
