### ISSUE TITLE
Null pointer in rtp.cc

### ISSUE THREAD

**Issue by Atlas42** [ultravideo/uvgRTP#220]
I had a segfault here :

https://github.com/ultravideo/uvgRTP/blob/f75942b0e5afab0692707cd6bc3cac9557c15f9e/src/rtp.cc#L323

The `(*out)->payload` is null, and if I am reading the code well, is only initialized a few lines after.

I believe the proper code should be:
`uint8_t padding_len = packet[size - 1];`
But I am not entirely sure.

**Comment by jrsnen** [comment]
We haven't tested the padding much. At least, it should not crash if the payload size is 0.

BR, Joni

**Comment by jrsnen** [comment]
Fixed by 69f869c6b6784f378a59fbeb70babf25174a9136. Thanks.
