### ISSUE TITLE
strange if statements

### ISSUE THREAD

**Issue by db-tech** [ultravideo/uvgRTP#23]
As I am checking the commit https://github.com/ultravideo/uvgRTP/commit/decde85859e8607242dfeb9a5b36666536c85c2a for the issue #12 I saw a lot of code like this:

```c++
if (!(pkt_dispatcher_ = new uvgrtp::pkt_dispatcher()))
        return free_resources(RTP_MEMORY_ERROR);
```

I am not sure I understand what this is supposed to do ?

**Comment by altonen** [comment]
Hi,

it tries to allocate memory for pkt_dispatcher_ object and if the allocation fails, i.e., nullptr is returned, the code frees all memory thus far allocated and returns an error code.

**Comment by altonen** [comment]
Although I just checked and it seems that new doesn't return nullptr ever (unlike malloc) but instead throws an exception so that code doesn't really make sense. I guess it should be fixed

**Comment by db-tech** [comment]
That why I asked :-)

**Comment by altonen** [comment]
We can use this issue. You can do it if you want, contributions are appreciated

**Comment by db-tech** [comment]
Ok, I will get to it but it ma take a while. I have two additional questions/comments.

1. I would probably replace some of those raw pointer with smart pointers. But I will do that in another PR. Otherwise this PullRequest will get to big ?!
2. I would like to do a lot of small changes and fixed of stuff I have found. Should I do those in one PR under one new issue ?

**Comment by db-tech** [comment]
I have another question.
I an error of "std::bad_alloc" happens because of a "new" call, I expect that we cannot recover from that or handle it in a useful way? 
So I would just let it through.
Any other opinion ?

**Comment by altonen** [comment]
Try to keep the commits small/self-contained so it'll be easier to bisect through if it every comes to that. As for PRs, I think it would be nicer if one PR would reference one issue so in that sense it would be nicer if this issue wouldn't be reused beyond this pointer issue and a new issue would be created for new improvements.

I think std::bad_alloc can be let through, yes.

**Comment by polusto** [comment]
Fixed by PR. Thanks!
