### ISSUE TITLE
Would using more C++ features be welcome ?

### ISSUE THREAD

**Issue by db-tech** [ultravideo/uvgRTP#24]
The source seems really "C-ish".
Is this because of some performance concerns or would a PR in this regard be welcome ?
For example, using smart pointer in some situations ?

**Comment by altonen** [comment]
Hi,

using more C++ features is very welcome. There's no great mystery behind the C-ishness of uvgRTP, it's just that I've been writing more C than C++ and I guess it shows.

**Comment by lhp-git** [comment]
Hi,
If you add more C++ features, please don't break the uvgRTP compilation with "old" compilers, at least C++11 and newer. Industrial projects use very stable OS (RHEL7 or Centos7 in my case) and don't update often. I wrote a pull request recently to fix the C++11 build, because I use uvgRTP for a development at work.

**Comment by db-tech** [comment]
I guess it is possible but unfortunate, C++17 has features this lib could really benefit from.
And always having an alternative for C++11 is to much of an effort in my opinion and makes the code ugly.

So I will just begin with some smaller things.
But if this the general approach, wouldn't it be better to just change the default to 11 in the CMake file (even so it would make me sad ;-))
The Crypto++ __has_include stuff could also be made in CMake.

**Comment by altonen** [comment]
I'm not sure if we want to tie uvgRTP to C++11 for all eternity either, it's quite an old standard after all. Maybe some version of uvgRTP could be the final C++11 release or there could be separate C++11 branch and some newer versions of uvgRTP/master branch could use newer features.
