### ISSUE TITLE
Wrong if statement or operator in h26x.cc

### ISSUE THREAD

**Issue by db-tech** [ultravideo/uvgRTP#28]
I just saw this code in h26x.cc

```C++
if (t1 && t4) {
                /* previous dword 0xxxxx0000 and current dword is 0x0001XXXX */
                if (t4) {
                    start_len = 4;
                    data[rpos] = lb;
                    return pos + 2;
                }
            /* Previous dwod was 0xXXXXXX00 */
            }
```

The second if `if (t4)` will always be true.

Is this just a useless if or could it be that this was meant to be a Bitwise & not a logical && ?
Keep in mint, I had no time to look of the logic of that code, just wanted to quickly report it so I don't forget it tomorrow.

**Comment by polusto** [comment]
Looks like the line referenced is this: https://github.com/ultravideo/uvgRTP/blob/bf8be9e85cb0627899526b80eb9a877a55f1abdc/src/formats/h26x.cc#L213

Yes, it should be fixed.

**Comment by polusto** [comment]
Honestly, I don't know which one of those is the wrong one XD. I would otherwise fix this.

**Comment by db-tech** [comment]
If the && is correct, then it does not matter but i have my doubts about that.

**Comment by jrsnen** [comment]
I fixed this and clarified the SCL function in general.
