### ISSUE TITLE
How to enable autodeallocation?

### ISSUE THREAD

**Issue by HikariS97** [ultravideo/uvgRTP#3]
I create sessions like this
`    sess_ = ctx_.create_session("127.0.0.1");`
`    send_ = sess_->create_stream(8888, 8889, RTP_FORMAT_GENERIC, RCE_FRAGMENT_GENERIC);`
`    recv_ = sess_->create_stream(8889, 8888, RTP_FORMAT_GENERIC, RCE_FRAGMENT_GENERIC);`

and the type of frame_s_ is const QVideoFrame &frame. I can receive frames by pull method, and reconstruct a QVideoFrame structure successfully. But it seems like the push_frame function disable the deallocation of videoframe buffer somehow. The program accumulates the memory  by step of 0.9MB. That's the size of one frame. 
I'm not clear about what's going on inside of push_frame function.  Can u give some advices about how does push_frame funcition make the deallocation of frame not work?
![微信截图_20200507145830](https://user-images.githubusercontent.com/48763518/81264091-6f3b0880-9073-11ea-8fa3-16c4f9df60e4.png)

**Comment by altonen** [comment]
hello,
why the deallocation is very strange. uvgRTP shouldn't hold any references to the input once push_frame() returns. According to Qt documentation, frames_s_.bits() is a uchar pointer so there should be no problem with deallocation unless Qt adds some magic reference counting which I find very unlikely.

Just to make sure, if you remove push_frame() entirely, the deallocation starts working again? Passing RTP_COPY to push_frame() might magically make it work because then the original pointer doesn't leave the initial push_frame(). It's still not a proper solution though.

I will have to investigate this and get back to you.

**Comment by HikariS97** [comment]
Hi,
If I remove push_frame() entirely, it works. It's just a experiment to test whether rtp lib can properly communicate with the frame data presented by QVideoAbstractSurface(yes, it works well except memroy leak).

I have also tested, if I created a new memory chunk, and use memcpy to copy data from frame.bits() to a new memory address. It seems if I only copy the memory, and use delete[] afterwards, the deallocation process of QVideoFrame is not affected. Then I unmap the frame, and call push_frame by using the New Address, the dealloction fails again. Maybe It's something wrong with multithreads process? I create ctx, session in the Constructor Func of subclass parent from QVideoAbstractSurface, and put only send & receive parts in a single func. According to above, I think it's maybe not a bug caused by QT, it's just some multithread insecurity caused by myself.

PS: The deallocation also failed when I passed RTP_COPY to push_frame(). I think memcpy takes the same functionality.

Here's the Constructor and Deconstructor functions of my RtpTest class and QVideoAbstractSurface class
![微信截图_20200508091141](https://user-images.githubusercontent.com/48763518/81359609-3307b680-910c-11ea-9beb-2fdd3bef65c0.png)

![微信截图_20200508091208](https://user-images.githubusercontent.com/48763518/81359614-356a1080-910c-11ea-9ed2-72a91492d4e6.png)

**Comment by altonen** [comment]
hello,
suggesting RTP_COPY was borderline desperate anyway so I'm not surprised it didn't work. Are you able to share your full sender/receiver code (Ie. all calls to uvgRTP)? Are you by any chance forgetting to deallocate the frame you get from pull_frame()? The problem should not be related to multithreading so I'm sure it's either uvgRTP's internals or the usage of the library itself that causes this problem.
I await your response.

**Comment by HikariS97** [comment]
Hi,
thanks for your remind. Yes, I forget to deallocate the memory occupied by pull_frame(). Sorry I just forget that. I just take the sending_general.cc as base code and no manual deallocation there.(I know it's in the example receiving_poll.cc.).

Thanks for your patience！
