### ISSUE TITLE
RFC 3550 RTCP: The fraction lost in RTCP report blocks is calculated incorrectly

### ISSUE THREAD

**Issue by jrsnen** [ultravideo/uvgRTP#30]
Fraction on this line: https://github.com/ultravideo/uvgRTP/blob/9ef02a72f891702f6cfb281613426bccc67c109f/src/rtcp.cc#L1240 is calculated incorrectly. See https://datatracker.ietf.org/doc/html/rfc3550#section-6.4.1 and https://datatracker.ietf.org/doc/html/rfc3550#appendix-A.3

This concept of RTCP received bytes is not found in the RFC and should be removed:
https://github.com/ultravideo/uvgRTP/blob/decde85859e8607242dfeb9a5b36666536c85c2a/include/rtcp.hh#L37

**Comment by tampsa** [comment]
Fixed by 371a3fa816591916282fe27d083a3dea7c2c1647
