### ISSUE TITLE
CMake installation rules for the project should be fixed

### ISSUE THREAD

**Issue by dkozinski** [ultravideo/uvgRTP#4]
It seems that  there is a bug in CMakeLists.txt.
Installation rules for header files doesn't work since the header source path is set wrong.

You should use "include/" instead of "src/" source path  to install header files.

Please replace /src directory with include/ in the CMakeLists.txt as follows:
install(DIRECTORY include/ DESTINATION ${PROJECT_BINARY_DIR}/include
                        FILES_MATCHING PATTERN "*.hh"

**Comment by altonen** [comment]
hi,
i've pushed a fix to master. Thank you for the bug report!
