### ISSUE TITLE
RTCP hook with member function pointer

### ISSUE THREAD

**Issue by wowaser** [ultravideo/uvgRTP#43]
Hello again, 

This is more of a question than an issue, but I've been struggling with this for a while now. Consider I have code:

```cpp
class myClass{
public:
    myClass(){
        session = ctx_.create_session("127.0.0.1");
        stream = session->create_stream(7777, 8888, RTP_FORMAT_GENERIC, 0);        
        (void)stream->get_rtcp()->install_receiver_hook(rtcpHook);//<- this is the problem, member function ptr
    }   
private:
    uvgrtp::context ctx;
    uvgrtp::session* session;
    uvgrtp::media_stream* stream;
    void rtcpHook(uvgrtp::frame::rtcp_receiver_report *frame){/body/}
}
```
I want to install a hook, which is a member function in this case. I have tried pretty much everything, like reinterpret casting, typedef, std::bind, etc. Nothing seems to correctly convert to the correct function pointer type. Could you explain to me how this is supposed to be done? Thanks

**Comment by polusto** [comment]
That is a good question. It seems that uvgRTP currently uses C-style interface for this so direct support for classes doesn't seem to exist. I'm not actually sure that using classes with rtcp is possible, but maybe @altonen can clarify?

The rtp install hook takes the void* arg as a parameter, which enables using a static function to solve this issue, but rtcp doesn't have this luxury. 

Unless I'm missing something, it looks like the public API of uvgRTP needs a new functions to support c++ classes. Only using singleton classes and classes as public variables works with the current rtcp api.

**Comment by polusto** [comment]
I will try to do this tomorrow. It seems very unfortunate, that classes are not supported with uvgRTP RTCP.

**Comment by wowaser** [comment]
Rtcp hooking works with static functions, tho. But a static hook isn't of much use, I need to access and modify the object.

**Comment by polusto** [comment]
I don't currently use rtcp, but I have plans to use and I too definitely need access to objects also. I'll see what I can do about this.

**Comment by polusto** [comment]
I added new hook functions to rtcp in 67e54644c483c14bc27acfb548b410620bf5cec8

I couldn't get receiver reports working for reason, but sender reports worked.

**Comment by wowaser** [comment]
@polusto So, how would I call the function in my example? I am still a little confused...
And what about the receiver reports? They are kinda the main reason to use rtcp reports

**Comment by wowaser** [comment]
```cpp
std::function<void(std::shared_ptr<uvgrtp::frame::rtcp_app_packet>)> func = std::bind(&myClass::appHook, this, std::placeholders::_1);
stream->get_rtcp()->install_app_hook(func);
```
Something like this?

**Comment by polusto** [comment]
Yes, your code looks correct. This is what I used in testing
```
std::function<void(std::shared_ptr<uvgrtp::frame::rtcp_sender_report>)> fp =
    std::bind(&UvgRTPReceiver::handle_rtcp, this, std::placeholders::_1);
watcher_.result()->get_rtcp()->install_sender_hook(fp);
```

As for the rtcp reports, I couldn't get them working. It may be that I did something wrong or that my recent changes broke the functionality somehow or it didn't work previously. I will look into it next week when I have more time, but you may test it if you can get it working.

**Comment by wowaser** [comment]
Hmm, I am getting a linker error on this line:
```cpp
Stream->get_rtcp()->install_sender_hook(fp);
```
With sender, receiver, and app hooks, any idea what can cause this? I have pulled the most recent changes. 
Should I include something else besides "lib.hh"?

**Comment by polusto** [comment]
Includes don't affect linker errors.

Have you updated the library and have you defined the hook function you are installing?

**Comment by wowaser** [comment]
No, I have not updated the binary, now everything works fine. Thanks

**Comment by wowaser** [comment]
@polusto have you had any success with rtcp reports? I am getting the following with the receiver reports:
![image](https://user-images.githubusercontent.com/70014877/125694188-300c7550-a560-4668-b6a8-9c01c8ce4a50.png)

So the in the receiver hook (the hook on the sender side) is called 
![image](https://user-images.githubusercontent.com/70014877/125694386-cb1cea56-9df0-424f-bb7a-aef656362e9a.png)
but the packet doesn't get processed for some reason. 

The sender reports aren't working at all for me

**Comment by polusto** [comment]
I created a new issue #59, where we can continue the discussion.
