### ISSUE TITLE
Sending and splitting frames

### ISSUE THREAD

**Issue by wowaser** [ultravideo/uvgRTP#45]
Hi,

I have a problem with sending frames using RTP_FORMAT_GENERIC with the RCE_FRAGMENT_GENERIC flag set. It works fine with low-quality videos, but higher quality produces an error: 
![image](https://user-images.githubusercontent.com/70014877/122911339-df801880-d35f-11eb-80fb-72db54663be7.png)

RCE_FRAGMENT_GENERIC splits the frame into ~1500 sized packets, and according to this error, the max number of chunks is 32. So the maximum allowed size of the frame is 1500*32 = 48000. Increasing the MTU solves this problem, but it is not realistic outside of the testing environment to increase MTU. 

The same happens when I try to use HEVC encoding (I printed out the size of the frame):
![image](https://user-images.githubusercontent.com/70014877/122912210-c166e800-d360-11eb-9e75-5da7ae897ea2.png)

Again, increasing the MTU solves this.

Is there a reason for the 32 part limit? What can I do to avoid this? Thanks

**Comment by polusto** [comment]
Newest master should have increased buffer size. Specifically bf8be9e85cb0627899526b80eb9a877a55f1abdc

A more permanent solution should be implemented, but that should help in the mean time.
