### ISSUE TITLE
How to save h.264 frames

### ISSUE THREAD

**Issue by robviaas** [ultravideo/uvgRTP#46]
If I pull h.264 frames directly from rtsp in a live stream, I can feed it through ffmpeg:
```ffmpeg -i rtsp://192.168.1.5/0/profile2/media.smp out.h264 ```

I can't understand how to do the same using this library. I'm able to go through the rtsp setup using libcurl, then capture bits with uvgrtp, but after I write them to file, they are unplayable by ffmpeg.
```
    uvgrtp::context ctx;
    uvgrtp::session *sess = ctx.create_session("127.0.0.1");
    uvgrtp::media_stream *vid = sess->create_stream(1234, 0, RTP_FORMAT_H264, RTP_NO_FLAGS);
    vid->install_receive_hook(nullptr, receive_hook);
...
void receive_hook(void *arg, uvgrtp::frame::rtp_frame *frame) {
    fout.write((const char*)frame->payload, frame->payload_len);
}
```

It appears as though they are no longer wrapped with NAL. The bits on my ffmpeg-grabbed file have the 4 byte 0x1 prefix, but when I'm writing via uvgrtp, they don't, though the next 4 bytes show that they clearly share some of the actual contents (and appear roughly the same size).
```
ffmeg hexdump -C output starts:
00000000  00 00 00 01 67 64 00 28

receive_hook hexdump -C output starts:
00000000  67 64 00 28 ac 1b 1a 80
```

Also, when I print out the frame sizes, they seem to contain frames that approximate inter- and intra- sizes, but also some other meta-type frames (usually 8 bytes):
```
len: 48
[RTPLIB][DEBUG][::call_aux_handlers] Received a corrupted packet!
len: 4
len: 26
len: 58134
len: 8
len: 3236
len: 8
len: 3109
len: 8
len: 3582
len: 8
```

What am I missing? I've looked for examples but came up short. I tried RTP_FORMAT_GENERIC and seemed to have similar results, and same with h.265.

**Comment by polusto** [comment]
Hi and thank you for the issue. 

I've been sort of wondering the same (what happens to NAL headers in uvgRTP and is it correct). I'm not familiar enough with uvgRTP to know the answer. Maybe @altonen can respond?

If not, I will take a look at the [specification](https://datatracker.ietf.org/doc/html/rfc6184) and try to figure it out. This will take maybe next week or the week after that.

**Comment by fador** [comment]
I think it's working as intended, since Annex B specifying the start code is not to be used in RTP:
`This payload specification can only be used to carry the "naked"  H.264 NAL unit stream over RTP and not the bitstream format discussed in Annex B of H.264. `
RTP has it's own headers to figure out the size of the NAL units so it would be redundant.

Solution to this is to write the start code before each frame to the output, something like:
```c
char temp[4] = {0,0,0,1};
fout.write((const char*)temp, 4);
```

**Comment by polusto** [comment]
@fador thanks for the info.

**Comment by altonen** [comment]
You can also provide `RCE_H26X_PREPEND_SC` when you're creating a media stream to instruct uvgRTP to automatically prepend a start code to frames. Unless there's a bug, uvgRTP doesn't touch any metadata but only removes the start codes which you must re-add as Marko already explained.

@polusto might also benefit from this flag with Kvazzup as you can remove the start code logic from UvgRtpReceiver

**Comment by fador** [comment]
@altonen Good to know there's a flag for that! ..but I didn't see the logic implemented for H.264

**Comment by wowaser** [comment]
Should we also consider the null byte mentioned in issue #20 (https://github.com/ultravideo/uvgRTP/issues/20)? 
Should it be +1 on sending and -1 on receiving?

**Comment by fador** [comment]
@wowaser actually that is only a problem with text strings, video data is just plain binary so there is no need for such. Also you could send it without the null byte and just add it when receiving to save some bandwidth, when you know you need it ;)

**Comment by robviaas** [comment]
Yes! Thank you @fador for the clarification. Adding those 4 bytes did the trick. Also thank you for the explanation about the smaller units. This info got me over the hump!

**Comment by polusto** [comment]
I also added the prepend start code support to h264 video in 06fdcd519bc62ac4d01df7692ebd12b8205afcff for even easier solution. I used the existing code, so it should work.
