### ISSUE TITLE
Adding dynamic payload type to examples

### ISSUE THREAD

**Issue by polusto** [ultravideo/uvgRTP#55]
Some codecs use predefined payload types, but many codecs use a dynamic payload type. Currently there is no way to set the dynamic payload number for Opus, VVC, HEVC or AVC, when all of these use a dynamic number. Instead the library forces the number to be some predetermined value.

See more details [here](https://en.wikipedia.org/wiki/RTP_payload_formats)

**Comment by altonen** [comment]
There is `RCC_DYN_PAYLOAD_TYPE` which you can use to define a dynamic payload type used for a stream. This simply overrides the the default payload set in `src/rtp.cc` with the value that user gives.

**Comment by polusto** [comment]
@altonen Thank for the info! In that case, this info could be added to the configuration and/or sending examples.
