### ISSUE TITLE
Failed to generate sender reports and receiver report has no blocks with unidirectional streams

### ISSUE THREAD

**Issue by polusto** [ultravideo/uvgRTP#59]
Sender reports are not generated and receiver reports have no report blocks.

![image](https://user-images.githubusercontent.com/6498638/125941367-24037d82-3fbe-4501-b239-13bb4a7a558d.png)

First error prevents the generation of sender reports and the second error means that receiver reports does not include any blocks.

Tested with unidirectional RTP stream. There are indications that bidirectional stream may work better.

**Comment by wowaser** [comment]
I haven't really had success with fixing this issue, what about you, @polusto? Also, is there a way to access RTCP reports manually, i.e. make them more frequent or modify the contents?

**Comment by polusto** [comment]
I've been focusing on improving the examples, but I will now start focusing on fixing the bugs starting with this one. Hopefully, I'll get at least some bugs fixed before my vacation. 

This problem seems to come from lack of testing for one-way/unidirectional streams. There is some mistake how sender reports are implemented, because I noticed that the explanation in the example is not correct. How I understand the RFC is that either sender or receiver reports should be always sent.

The problem seems to be lack of blocks/senders for both sender and receiver reports.

Changing the frequency sounds like a good idea if the RFC allows it. It could be implemented via some sort of context flag system similar to RTP. I will create an issue.

**Comment by polusto** [comment]
I don't think the contents of RTCP message can be modified at this point. I'm not very familiar with RTCP, what is the reason you want to modify the contents?

**Comment by polusto** [comment]
The sender check it complains about seems to be wrong. I will remove it and test it tomorrow. I also tried to improve rtcp report timing mentioned in issue #22

**Comment by wowaser** [comment]
Maybe content modification was too farfetched, but the adjustable frequency of RTCP reports is definitely something that is of interest. 

I used to be able to create RCTP receiver reports through a normal (non-member) function like a month ago. Maybe some new filter in recent commits is not letting them through or something. As per issue #22, I just had a misunderstanding of how the RTCP reports work and thought that they are sent as a response to every incoming frame. Or are you talking about the continuation of RCTP reports when there is no incoming traffic?

**Comment by wowaser** [comment]
I found this excerpt on the internet: 

> The RTCP reporting interval is randomized to prevent unintended synchronization of reporting. The recommended minimum RTCP report interval per station is 5 seconds. Stations should not transmit RTCP reports more often than once every 5 seconds.

**Comment by altonen** [comment]
I don't think you can decrease the interval of reports without breaking the spec. RTCP was designed in the early 2000 and if you read the rationale behind this back-off mechanism, what they had in mind was media stream sessions with hundreds or even thousands of participants. Decreasing the interval in such scenarios, especially in low-bandwidth networks, would likely not result in something we would call a usable stream.

To be honest, I think you could built a better, ad-hoc session statistics gathering and distribution mechanism on top of RTP because you wouldn't have to conform to all of these, somewhat peculiar and outdated, rules. If you could somehow tap into uvgRTP's internal RTCP state, you could maybe even send this session statistics packets in-band by utilizing custom extension headers. Food for thought if these RTCP rules are too restricting.

**Comment by polusto** [comment]
The problem is that reception reports are actually sent and received, but they don't have any report blocks. It is possible that my refactoring of RTCP broke something between now and month ago.

I was talking about synchronization of sending. It will be improved slightly in the future. I closed #22 since there didn't seem to be any direct problems in it.

As @altonen said, [RFC 3550](https://datatracker.ietf.org/doc/html/rfc3550#section-6.2) which we are trying to implement here, doesn't say anything about randomization. There is an involved calculation about the interval, but then the minimum is set to 5 seconds which is reached when bandwidth is 76 kbit/s or higher. So I'm guessing the calculation was left out since most connections will reach that?

5 seconds is only a recommendation, so if user wants to change this, I would say they can do that. That way also if the user really wants to support the interval calculation, they can implement it themselves (it would also be nice to do this at some point ourselves just so that we can say we support the full RFC). Please note that the spec says that all participants should have them same RTCP interval! I couldn't find any reference to random start delay other that that there should be some delay.

If there are any deviations from RFC 3550, those will be considered bugs and fixed. At the very least it should be possible for the user to fill in the holes left in the library (and those holes should be documented).

**Comment by polusto** [comment]
I think I figured out all the problems in this issue. I will push the fixes tomorrow.

**Comment by polusto** [comment]
Should be fixed in newest master. If anyone notices more issues with RTCP, please create a new issue.

**Comment by polusto** [comment]
As a side note to @wowaser, I'll be on vacation for the next couple of weeks. @altonen or @fador will hopefully have time to answer any further issues in the mean time and if not, I'll get back to working towards end of August.
