### ISSUE TITLE
session/media_stream API for only receiving in case the sender is not known/needed

### ISSUE THREAD

**Issue by jrsnen** [ultravideo/uvgRTP#62]
When creating the uvgRTP session, one needs to always specify the remote address and when creating the media streamer, the remote port must always be specified. There is a common scenario where only want to listen to specific address on specific port and this is not possible at the moment.

Settings something random (like localhost) to remote address probably works, but this is not a good solution.

**Comment by lubertRoft** [comment]
regarding the receiving of messages, I tried to pull data from a port on a remote address but it was not possible, could you explain why or if it is possible using your library?

**Comment by polusto** [comment]
@lubertRoft What addresses and ports did you use? Was the firewall open or did you use another solution?
 
uvgRTP pull_frame should work if the specified address/port combinations are correct and a firewall does not block the transmission.

**Comment by lubertRoft** [comment]
hello @polusto, thank you very much for your quick reply, I will try that out.

**Comment by polusto** [comment]
If you are talking about firewall, the trick is to send from the same port as you are receiving. If the transmission is only one way, you may want to check out binding example, which sends hole-punching packets from receiver to sender. Another option is just to disable firewall for the specific port and application.

**Comment by lubertRoft** [comment]
Sorry for the late reply, I didn't try your hint, as I changed the architecture towards pulling only from local ports; also because I didn't want to fiddle with the firewall...

**Comment by jrsnen** [comment]
This issue is more fully discussed in #83. Closing
