### ISSUE TITLE
MacOS compilation

### ISSUE THREAD

**Issue by shrikky** [ultravideo/uvgRTP#70]
Hi I am not able to compile for MacOS. Looks like windows specific files are trying to be compiled?

In file included from /Users/lakvijay/Downloads/uvgRTP-master/src/clock.cc:3:
/Users/lakvijay/Downloads/uvgRTP-master/include/debug.hh:88:15: error: use of undeclared identifier 'WSAGetLastError'
        NULL, WSAGetLastError(),
              ^
/Users/lakvijay/Downloads/uvgRTP-master/include/debug.hh:90:10: error: use of undeclared identifier 'LPWSTR'
        (LPWSTR)&s, 0, NULL
         ^
/Users/lakvijay/Downloads/uvgRTP-master/include/debug.hh:87:9: error: use of undeclared identifier 'FORMAT_MESSAGE_ALLOCATE_BUFFER'
        FORMAT_MESSAGE_ALLOCATE_BUFFER | FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS,
        ^
/Users/lakvijay/Downloads/uvgRTP-master/include/debug.hh:87:42: error: use of undeclared identifier 'FORMAT_MESSAGE_FROM_SYSTEM'
        FORMAT_MESSAGE_ALLOCATE_BUFFER | FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS,
                                         ^
/Users/lakvijay/Downloads/uvgRTP-master/include/debug.hh:87:71: error: use of undeclared identifier 'FORMAT_MESSAGE_IGNORE_INSERTS'
        FORMAT_MESSAGE_ALLOCATE_BUFFER | FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS,
                                                                      ^
/Users/lakvijay/Downloads/uvgRTP-master/include/debug.hh:89:20: error: use of undeclared identifier 'LANG_NEUTRAL'
        MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT),
                   ^
/Users/lakvijay/Downloads/uvgRTP-master/include/debug.hh:89:34: error: use of undeclared identifier 'SUBLANG_DEFAULT'
        MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT),
                                 ^
/Users/lakvijay/Downloads/uvgRTP-master/include/debug.hh:94:43: error: use of undeclared identifier 'WSAGetLastError'
        LOG_ERROR("%s: %ls %d\n", aux, s, WSAGetLastError());
                                          ^
/Users/lakvijay/Downloads/uvgRTP-master/include/debug.hh:96:34: error: use of undeclared identifier 'WSAGetLastError'
        LOG_ERROR("%ls %d\n", s, WSAGetLastError());
                                 ^
/Users/lakvijay/Downloads/uvgRTP-master/include/debug.hh:98:5: error: use of undeclared identifier 'LocalFree'
    LocalFree(s);
    ^

**Comment by altonen** [comment]
You may be the first person compiling uvgRTP on MacOS so it's no surprise really that it isn't working. There is a CMake redesign PR pending but it also seems to have MacOS support missing at the moment. I'd wait for that PR to be merged but feel free to contribute build support for MacOS if you can.

**Comment by shrikky** [comment]
Sure, might be above my cmake skills, but I will try digging into this more and if I crack this, I will push this change. If anyone can help me with suggestions, I would love to put time and figure this out.

**Comment by fador** [comment]
If the `debug.hh` is the only problem, you can try to change the code just a bit to compile the linux version also in macos.

So the original is like:
```
#ifdef __linux__
  <linux stuff>
#else
   <windows stuff>
#endif
```

It might work if you change it to:
```
#ifdef _WIN32
  <windows stuff>  
#else
  <linux stuff> 
#endif
```

**Comment by db-tech** [comment]
You could Try my branch from the PR. I did not add some Mac OS specifics because I do not have a Mac. But, building might still work. I can fix the missing stuff after the PR is in if you are willing to test it :-)

**Comment by db-tech** [comment]
fador was faster :-). of course, source problems for Mac are not fixed in that branch.

**Comment by themightyoarfish** [comment]
I get other errors, both with clang and gcc 11 on macos (current master):
```
uvgRTP/include/socket.hh:163:28: error: field 'header_' has incomplete type 'uvgrtp::mmsghdr'
  163 |             struct mmsghdr header_;
```

plus many many warnings
```
uvgRTP/src/rtp.cc:198:48: warning: ISO C++11 requires at least one argument for the "..." in a variadic macro
  198 |         LOG_DEBUG("frame contains csrc entries");
```

**Comment by themightyoarfish** [comment]
Also other bits are not osx compatible, like the `struckt mmsghdr` used in `socket.hh` which does not exist on osx. 
I'm a bit confused; the code explicitly branches on `__APPLE__` in places, but is not compilable on osx, perhaps this should be documented?

**Comment by polusto** [comment]
@themightyoarfish Sorry about that, the OS support was completely missing from readme, I added it now. Currently, macOS is not supported, unfortunately. We are open to PRs in this regard, but at the moment we have no one able to work on this.
