### ISSUE TITLE
libuvgrtp.a(queue.cc.o): requires dynamic R_X86_64_PC32 reloc against

### ISSUE THREAD

**Issue by plusai-youzhou** [ultravideo/uvgRTP#81]
Hi, 

I built the uvgrtp lib `cmake -DDISABLE_CRYPTO=1 . && make package` without problem with [commit](https://github.com/ultravideo/uvgRTP/tree/50120fa271cde1321570af84a72c66f4dd176c9d). But when I try to include it into my project, below error appeared. After manually adding `set(CMAKE_POSITION_INDEPENDENT_CODE ON)` into the uvgrtp makefile, the error is gone. Not sure if this is the right way to resolve the problem.

`
/usr/bin/ld.gold: error: /usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libuvgrtp.a(queue.cc.o): requires dynamic R_X86_64_PC32 reloc against '_ZSt11__addressofINSt8__detail10_Hash_nodeISt4pairIKjPN6uvgrtp11transactionEELb0EEEEPT_RS9_' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libuvgrtp.a(queue.cc.o): requires dynamic R_X86_64_PC32 reloc against '_ZNSt8__detail21_Hash_node_value_baseISt4pairIKjPN6uvgrtp11transactionEEE4_M_vEv' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libuvgrtp.a(queue.cc.o): requires dynamic R_X86_64_PC32 reloc against '_ZNSt8__detail21_Hashtable_ebo_helperILi0ESt8equal_toIjELb1EE7_S_cgetERKS3_' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libuvgrtp.a(queue.cc.o): requires dynamic R_X86_64_PC32 reloc against '_ZNSt8__detail21_Hashtable_ebo_helperILi0ENS_10_Select1stELb1EE7_S_cgetERKS2_' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libuvgrtp.a(queue.cc.o): requires dynamic R_X86_64_PC32 reloc against '_ZNKSt8__detail15_Hash_code_baseIjSt4pairIKjPN6uvgrtp11transactionEENS_10_Select1stESt4hashIjENS_18_Mod_range_hashingENS_20_Default_ranged_hashELb0EE5_M_h2Ev' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libuvgrtp.a(queue.cc.o): requires dynamic R_X86_64_PC32 reloc against '_ZSt4copyISt13move_iteratorIPPN6uvgrtp11transactionEES4_ET0_T_S7_S6_' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libuvgrtp.a(queue.cc.o): requires dynamic R_X86_64_PC32 reloc against '_ZStneIPSt6vectorISt4pairImPhESaIS3_EEEbRKSt13move_iteratorIT_ESB_' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libuvgrtp.a(queue.cc.o): requires dynamic R_X86_64_PC32 reloc against '_ZNK9__gnu_cxx13new_allocatorINSt8__detail10_Hash_nodeISt4pairIKjPN6uvgrtp11transactionEELb0EEEE8max_sizeEv' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libuvgrtp.a(queue.cc.o): requires dynamic R_X86_64_PC32 reloc against '_ZSt7forwardISt4pairIjPN6uvgrtp11transactionEEEOT_RNSt16remove_referenceIS5_E4typeE' which may overflow at runtime; recompile with -fPIC
`

**Comment by jrsnen** [comment]
Hi and welcome to using uvgRTP.

Have you tried compiling with ```-fPIC``` as the errors suggests?

I'm also not familiar with the make package command. You don't seem to be following our [build instructions](https://github.com/ultravideo/uvgRTP/blob/master/BUILDING.md). Is there a reason, or am I missing something?

Could the problem be that you are linking to a static library into a shared one? With GCC, a shared version of uvgRTP can also be built using a parameter. I think the parameter is ```-DBUILD_SHARED_LIBS=YES```. I haven't yet had the time to document and test it much, but it should work.

**Comment by plusai-youzhou** [comment]
Thanks for the fast response, Joni!
`set(CMAKE_POSITION_INDEPENDENT_CODE ON) ` is a former way to add flag `-fPIC`. They works the same.

About `make package`, my project requires the separation and archiving of third party libs, so I chose `make package` instead of `make install`. Actually a deb package more preferred, though it is not available yet. 

Thanks for the hint on the shared lib creation. Didn't know uvgrtp provides such. Will definitely try it out.

**Comment by jrsnen** [comment]
Closing as no response to question. In-source builds are not supported at this point.
