### ISSUE TITLE
H26x Parser unable to parse common NAL structure

### ISSUE THREAD

**Issue by jhkimura** [ultravideo/uvgRTP#85]
The H26x processing is unable to process a common NAL layout containing an Access Unit Delimiter.  The following is an example beginning of an H264 frame where the H26x processing returns an RTP_INVALID_VALUE:

00 00 00 01 09 10 00 00 00 01 27 64 00 2A AC 2B 40 3C 01 13 F2 E0 2D 40 40 40 50 00 00 3E 90 00 1D 4C 0E 84 00 1E 84 00 00 7A 12 1B DE F8 D0 80 03 D0 80 00 0F 42 43 7B DF 0E D0 E1 95

Notice the start code followed by the NAL-Access Unit Delimiter followed by another start code.  This is a common for H26x streams.  This effectively causes the data_len on line 316 of h26x.cc to return RTP_INVALID_VALUE due to the length of data being less than 3.   

`    if (data_len <= 3) 
        return RTP_INVALID_VALUE;
`

The expected behavior would be to continue processing the rest of the H264 stream instead of erroring out the entire frame.

I couldn't find any uvgRTP documentation pertaining to this so I assume it is a bug.

**Comment by jrsnen** [comment]
Thank you for this issue! Can you confirm that 2f19768ed22e0eb6ebe206f3f6002897dac5175e fixes this issue?

**Comment by jhkimura** [comment]
I pulled the head of master and this seems to have fixed it.  Thank you.  There was another fix in the latest master that fixed the small packet handling.  Thank you very much.
