### ISSUE TITLE
Problem sending .png-image read-in data

### ISSUE THREAD

**Issue by lubertRoft** [ultravideo/uvgRTP#87]
Hello,

I am reading .png-images from disk into memory using the stb_image.h-library. This seems to work properly as I can read out pixel values from the image array which correspond to what I get out of gimp for the selected pixel. But as soon as I try to send those images over the network with uvgRTP it throws a segmentation fault. Do you guys know this problem?

Best regards,
Robert

**Comment by jrsnen** [comment]
Hi.

At least I'm unaware of such crashes. Assuming the input data is not invalid, there shouldn't be a crash, but all those problems have not yet been ironed out from uvgRTP. I'm assuming you are using the generic sender.

Can you run the code through a debugger to get a sense where the crash happens?

**Comment by lubertRoft** [comment]
Thank you for the quick reply!

I will try to walk through it, but I am also wondering, what invalid value actually means?

**Comment by fador** [comment]
Since it also sounds you are sending a lot of data, is the fragmentation flag enabled in the session?
You should have it initialized something like this:
```C
sess->create_stream(8888, 8889, RTP_FORMAT_GENERIC, RCE_FRAGMENT_GENERIC);
```

**Comment by jrsnen** [comment]
@lubertRoft I just meant that the pointer given uvgRTP is valid and does not point to unreserved memory. This is something that is uvgRTP does not guard against.

**Comment by lubertRoft** [comment]
@fador,@jrsnen: thanks for the hint, I forgot that there is the possibility of using generic frames, that solved the problem!
@jrsnen: ok, I definitely know that the pointer is pointing to valid memory. But I have a more general question: is there some kind of data that can not be send using RTP_FORMAT_H265?

**Comment by jrsnen** [comment]
@fador @lubertRoft Yes, only H265 data is supported for RTP_FORMAT_H265. It probably shouldn't crash if other kinds of data are inputted, but it is not meant to do anything sensible in those situations.
