### ISSUE TITLE
Frames do not get delivered with high quality 4K HEVC stream

### ISSUE THREAD

**Issue by jrsnen** [ultravideo/uvgRTP#88]
I (and others) have encountered multiple times problems with 4K streams where the frame size is relatively large. 4K video with high QP values seem to work, as do lower resolution sequences. I would suspect the cause is somewhere in formats/h26x area.

This has worked with uvgRTP in the past. I tested 2.0 release and if I didn't make a mistake, the error was also present there.

* Affect both Linux and Windows operating systems.
* FPS does not affect the problem, only the frame size seems to affect it
* The problem is not deterministic, meaning that for different runs of the same encoded sequence, the results vary
* Caused by 706ff9796a0328a87080a49867d40faea15da2d8

**Comment by altonen** [comment]
Is it possible that the 4K video saturates upload/download bandwidth? Increasing socket buffers and TX/RX queues and confirming that it still occurs may be indication that there is actually something wrong with H26X. Best way to confirm this is an actual uvgRTP issue is to stream a 4K stream in localhost. Anyway, if this is a uvgRTP issue and it has worked in the past, it's easy to bisect the history and find the bug. With everything going on right now, I unfortunately don't have the time to do that.

**Comment by jrsnen** [comment]
At least ifconfig does not indicate that packets are lost. I have also heard that this exact issue is also present on Windows in the same way, so I would suspect this is an uvgRTP issue.

**Comment by jrsnen** [comment]
For me this issue is not a critical one at this moment, but it should be fixed in the near future.

**Comment by altonen** [comment]
So this is reproducible in your 10 Gbit network with high-end machines? I think `ifconfig` reports only the packets that are dropped by the kernel, so anything lost on the wire/maybe even NIC's internal buffers are not reported. Anyway, honestly I don't see how this relates to H26X because the code is same for high- and low-bandwidth streams. Something may be amiss in the buffering of either packet dispatcher/format's own frame buffer if this truly is a uvgRTP issue. There's also the 94 MB hard limit for fragmented frames but I don't think you're hitting that.

**Comment by jrsnen** [comment]
Yes, this is reproducible on several machines. FPS was low (30) and doesn't seem to be the cause. The issue seems to be directly correlated with frame size.

**Comment by jrsnen** [comment]
The issue first appears in 706ff9796a0328a87080a49867d40faea15da2d8

**Comment by altonen** [comment]
If you set both `tv_sec` and `tv_usec` to zero on each iteration or remove the `select()` entirely, 4K stream works fine?

**Comment by jrsnen** [comment]
@altonen I tested both options and they both work, but they both also cause the CPU usage to jump to 100%, which is not good.

**Comment by altonen** [comment]
That sounds really bad then.

It could be that the packet dispatcher is not optimized enough for 4K streams, i.e., the architecture is not 100% optimal for receiving such high-quality stream. Honestly, sleeping 1ms and 3ms doesn't sound like much of a difference so unfortunately this may require a major rework of the receiver architecture. If you're able to pin-point any location where most of the time is spent during packet reception, I can try optimizing it in an effort to save time on refactoring the receiver code, as opposed to just straight up rewriting all of the receiving code.

**Comment by jrsnen** [comment]
I managed to improve the situation considerably (and improve the general reliability of uvgRTP), but packets are still lost compared to busy looping (timeout=0) with receive thread.

**Comment by jrsnen** [comment]
My yesterday's commit didn't work well with low quality 4K streams, but now it should be fixed. I really wish this could be further improved more somehow. I have been testing using our performance testing framework (need two Linux machines in LAN): https://github.com/ultravideo/rtp-benchmarks

Currently, with almost all cases, at least around 80% of runs are successful (600 4K frames with no lost packets). The worst is when low quality (QP = 37) video is streamed at high fps (300+) and the best results are gotten when QP 27-37 is streamed at low fps values (~30 fps). QP 22 results are somewhere in between. Currently, there are almost always some frames lost, and I haven't tested this with the latest version, but for the busy loop version, 100% of runs are successful.

@altonen wasn't there a version of uvgRTP at some point that could get all the frames without 100% CPU usage?

**Comment by altonen** [comment]
Calling `select()` could be the problem here and if the attached patch is applied on top of b9de6ad8c27e8ec015eaeea7f156569c30fb2a2a I can get acceptable receive throughput out of the library. There seems to have been some performance regression in the last few months, at least the sender side has slowed down quite a bit according to my local benchmark. Very simple send test for commit f6b029c75fa63ef2590c8ce3b5591fac5fa55ca4 gives me the following output:

```sh
rtp-benchmarks >> uvgrtp/sender 1 1 800 1
411410113 bytes, 411410 kB, 411 MB took 900 ms 0 s
```
and for commit b9de6ad8c27e8ec015eaeea7f156569c30fb2a2a  it gives the following output:
```sh
rtp-benchmarks >> uvgrtp/sender 1 1 800 1
[uvgRTP][INFO][::context] uvgRTP version: 2.0.1-b9de6ad
411410113 bytes, 411410 kB, 411 MB took 1398 ms 1 s
```
I don't know could this be in any way a contributing factor to these frame drops but I think may be worth investigating why it takes ~600ms more time to send the same file. If the sender is not able to send the stream at an acceptable FPS then the receiver may drop the frames as they are coming late. And if that is combined with whatever problems the receiver has with busylooping or whatever, it's the perfect storm.

```diff
diff --git a/src/pkt_dispatch.cc b/src/pkt_dispatch.cc
index 7f411bf..7fe37d9 100644
--- a/src/pkt_dispatch.cc
+++ b/src/pkt_dispatch.cc
@@ -295,23 +295,23 @@ void uvgrtp::pkt_dispatcher::runner(uvgrtp::socket *socket, int flags)
 
     while (!runner_should_stop_) {
         /* reset state before each call */
-        struct timeval t_val;
-        t_val.tv_sec  = 0;
-        t_val.tv_usec = 1500;
-        FD_SET(socket->get_raw_socket(), &read_fds);
+        // struct timeval t_val;
+        // t_val.tv_sec  = 0;
+        // t_val.tv_usec = 1500;
+        // FD_SET(socket->get_raw_socket(), &read_fds);
 
-        int sret = ::select((int)socket->get_raw_socket() + 1, &read_fds, nullptr, nullptr, &t_val);
+        // int sret = ::select((int)socket->get_raw_socket() + 1, &read_fds, nullptr, nullptr, &t_val);
 
-        if (sret < 0) {
-            log_platform_error("select(2) failed");
-            break;
-        }
+        // if (sret < 0) {
+        //     log_platform_error("select(2) failed");
+        //     break;
+        // }
 
         rtp_error_t ret = RTP_OK;
-        do {
+        // do {
             int nread = 0;
             
-            if ((ret = socket->recvfrom(recv_buffer, recv_buffer_len, MSG_DONTWAIT, &nread)) == RTP_INTERRUPTED)
+            if ((ret = socket->recvfrom(recv_buffer, recv_buffer_len, 0/*MSG_DONTWAIT*/, &nread)) == RTP_INTERRUPTED)
                 break;
 
             if (ret != RTP_OK) {
@@ -345,7 +345,7 @@ void uvgrtp::pkt_dispatcher::runner(uvgrtp::socket *socket, int flags)
                         break;
                 }
             }
-        } while (ret == RTP_OK);
+        // } while (ret == RTP_OK);
     }
     delete[] recv_buffer;
 }
```

**Comment by jrsnen** [comment]
@altonen What is the CPU usage of that patch?

**Comment by jrsnen** [comment]
I tested different flags for the recvfrom, but none of them improved the situation (no flag came the closest, but it was still much worse than master). Considering how well the master works, I will close this issue because I lack the knowledge to improve this further and I don't have the time to investigate this more. Naturally, I welcome all clear improvements on the master, especially if some code can receive all frames without causing 100% CPU usage for the thread. The master is very close to this at the moment.

**Comment by altonen** [comment]
> @altonen What is the CPU usage of that patch?

It was around 40%
