### ISSUE TITLE
uvgRTP installation on Xnix for package-config

### ISSUE THREAD

**Issue by jheo4** [ultravideo/uvgRTP#9]
Hi all. I'm currently using uvgRTP in my research project.

Since my project has many dependencies, I manage them in the CMake script with [pkg-config](https://www.freedesktop.org/wiki/Software/pkg-config/). As you may know, pkg-config will find a library by its name and add all the flags for the linker and include path to the compile commands. To make that work, pkg-config requires .pc file in PKG_CONFIG_PATH such as /usr/local/lib/pkgconfig.

Till now, I'm using my forked repo and wrote the CMake scripts in that repo. It gets a .in configure file, generate a .pc file, and copy it to the proper location. If you are fine, I'd like to create a PR for this issue.

Thanks,
Jin

**Comment by altonen** [comment]
Great that you have found uvgRTP useful in your research! Feel free to open a pull request and I'll merge it if it looks okay

**Comment by jheo4** [comment]
Thanks for your quick response! I just created a PR. Please check it and feel free to put any comment on the PR when you are available. BTW, I really appreciate your work. This project is AWESOME. While using uvgRTP, I have faced a couple of issues. After checking them more, I will submit issues and work on them. Thanks!

**Comment by altonen** [comment]
Thank you for your kind words and for your contribution to uvgRTP! Unfortunately some of the features of uvgRTP have not been tested very rigorously so if you encounter more bugs/issues, please open a pull request for them. I'll close this issue and we can continue discussion in the pull request.
