### ISSUE TITLE
H264 Start Code Processing Skips some start codes.

### ISSUE THREAD

**Issue by jhkimura** [ultravideo/uvgRTP#90]
After further investigation, it seems I have found another issue with the start code processing and its handling of 3 byte start codes. consider the following set of bytes:

	ptr[0]	0x69 'i'	
	ptr[1]	0x37 '7'	
	ptr[2]	0xf9 'ù'	
	ptr[3]	0x4b 'K'	
	ptr[4]	0xe7 'ç'	
	ptr[5]	0x81 '�'	
	ptr[6]	0x00 '\0'	
	ptr[7]	0x00 '\0'	
	ptr[8]	0x01 '\x1'
The find_h26x_start_code located:

https://github.com/ultravideo/uvgRTP/blob/b9de6ad8c27e8ec015eaeea7f156569c30fb2a2a/src/formats/h26x.cc#L291

 offset = find_h26x_start_code(data, data_len, offset, start_len); 
The function misses processing the start code in the above situation. This is due to the technique used for finding zero's and it's 4 byte alignment. After debugging the code manually, I can see the 64bit scanning detecting the potential bytes and throttling into the 32bit comparison check. However, the 4 byte aligned processing for determining start code scenarios is unable to see it and moves along because the start code rides on the boundary. When compared to FFMPEG's processing, I have verified that FFMPEG is able to detect this scenario and divide the NALU appropriately.

I do not currently have an elegant solution to this issue that will maintain the same performance.

**Comment by jrsnen** [comment]
@jhkimura Thanks!
