### ISSUE TITLE
Is broadcast supported ?

### ISSUE THREAD

**Issue by gjaegy** [ultravideo/uvgRTP#94]
This is not really an issue, but rather a question... 
Is it possible to broadcast the stream using remote IP in the reserved range [224.0.0.0 - 239.255.255.255] ? 
Thanks a lot !

**Comment by altonen** [comment]
I have never tried it but somebody reported a while ago that they were able to use multicast and that would make me think that broadcast would also work.

**Comment by bcizmeci** [comment]
Is it possible to get sample code or documentation for multicasting?

**Comment by altonen** [comment]
I don't have an access to a setup that would allow me to test multicast at the moment but it should work by just binding to a multicast address and sending and receiving data to/from that address.
