### ISSUE TITLE
Socket Read & Write Buffers

### ISSUE THREAD

**Issue by bcizmeci** [ultravideo/uvgRTP#98]
In your paper, you mentioned that the Socket W&R buffers could be increased if the application has to send & receive the packets faster than the OS. Does this happen for example the application has to send & receive 1kHz and the OS frequency is slower such as 250Hz. 

If possible, could you please give some instructions on how to modify these OS buffers? and How do you decide these parameters?
Sender side: net.core.wmem_default, net.core.wmem_max
Receiver side: net.core.rmem_default, net.core.rmem_max

**Comment by jrsnen** [comment]
@bcizmeci I have some difficulty understanding your question. The buffer increase is only necessary for a very specific kind of streams, where the amount of data exceeds the temporary read possibilities of the receiver (4K video and above). We have not investigated what happens in low power CPU environments, but I would assume there is no need to increase buffers. If you continuously send more data than the receiver can actually handle, then increasing the buffers is not a solution I would recommend (instead, I would recommend sending less data or increasing the CPU power of the receiver).

I would first test the situation if there are any problems. In case you need to increase the buffers, how it can be done is shown in this example: https://github.com/ultravideo/uvgRTP/blob/master/docs/examples/configuration.cc

**Comment by bcizmeci** [comment]
Thanks a lot!
