### ISSUE TITLE
HEVC streaming with RTP_FORMAT_H265

### ISSUE THREAD

**Issue by bcizmeci** [ultravideo/uvgRTP#99]
I set up a basic point-to-point streaming setup (encoder -uvgrtp - decoder) however, the received frames are not decoded when they are received. When I switch to RTP_FORMAT_GENERIC, everything works fine but somewhat RTP_FORMAT_H265 does not work. 
How can I debug this? Do you have a suggestion or a tool to analyze this issue?

**Comment by jrsnen** [comment]
@bcizmeci Are you adding start codes yourself to the NAL units? There is also a flag for this, but currently it does not work with all NAL types.

**Comment by jrsnen** [comment]
By default, RTP removes the 0001 start code from all NAL units, which often means the decoder can't decode it.

**Comment by bcizmeci** [comment]
Yes, I tried to enable adding the start codes by setting the flag "RCE_H26X_PREPEND_SC". I realized that it is removing the start codes after analyzing a working stream (RTP_FORMAT_GENERIC) with a stream analyzer tool and a hex editor for the non-working stream (RTP_FORMAT_H265).  

What is the best way to fix this? I will check whether I can change the NAL type through the encoder configurations or not. Maybe it would be good to know which NAL types you support for the current version.

**Comment by jrsnen** [comment]
For me the problem was VPS, SPS and PPS:

```
  if (type_ == HEVCVIDEO &&
      ((frame->payload[0] >> 1) == 32 || // VPS
      ( frame->payload[0] >> 1) == 33 || // SPS
      ( frame->payload[0] >> 1) == 34))  // PPS
```

Currently, I append 0001 to all these frames I get from uvgRTP. Another alternative is to not use the flag and just append start codes to all RTP frames.

All NAL types should definitely get 0001 with the RCE_H26X_PREPEND_SC flag. The issue is discussed in #96.

**Comment by jrsnen** [comment]
Shown here: https://github.com/ultravideo/kvazzup/blob/a317e34d078f8b3e7baeede3f118032e177663a1/src/media/delivery/uvgrtpreceiver.cpp#L76

**Comment by bcizmeci** [comment]
@jrsnen Thanks a lot! Appending the start code definitely solved the problem for the current stage. I actually realized that I had to append the start code for another RTP streaming implementation.

**Comment by jrsnen** [comment]
@altonen thanks! With your suggestion, I implemented NAL start codes also to aggregate packets.

@bcizmeci now simple using the RCE_H26X_PREPEND_SC flag should be enough to decode the stream and is the recommended way of doing this since I don't think it uses any extra memory copies.
